name: CICD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Login to docker hub
        run: docker login -u ${{secrets.radhikaschude}} -p ${{secrets.Anadhika@1234}}

      - name: Build docker image
        run: docker build -t radhikaschude/ScrumMasterUserManagment .

      - name: Publish image to docker hub
        run: docker push radhikaschude/ScrumMasterUserManagment:latest

  deploy-to-qa:
    needs: build
    runs-on: aws-ec2 # Use appropriate OS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Login to Docker Hub
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull Image from Docker Hub
        run: docker pull radhikaschude/ScrumMasterUserManagment:latest

      - name: Stop and Remove Old Container
        run: |
          docker stop springboot-example-container || true
          docker rm springboot-example-container || true

      - name: Run Docker Container
        run: |
          docker run -d -p 8080:8080 --restart unless-stopped --name springboot-example-container radhikaschude/ScrumMasterUserManagment:latest
